/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "division.h"

bool_t
xdr_div_rpc_1_argument (XDR *xdrs, div_rpc_1_argument *objp)
{
	 if (!xdr_long (xdrs, &objp->divisor))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->dividendo))
		 return FALSE;
	return TRUE;
}
