/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "division.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

long *
div_rpc_1(long divisor, long dividendo,  CLIENT *clnt)
{
	div_rpc_1_argument arg;
	static long clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.divisor = divisor;
	arg.dividendo = dividendo;
	if (clnt_call (clnt, DIV_RPC, (xdrproc_t) xdr_div_rpc_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_long, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
