program DIV_PROG {
    version TP4 {
        long DIV_RPC(long divisor, long dividendo) = 1;    /* procedure number = 1 */
    } = 1;                          /* version number = 1 */
} = 0x31234567;   