/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "division.h"

long *
div_rpc_1_svc(long divisor, long dividendo,  struct svc_req *rqstp)
{
	static long  result;
	printf("Handling %.2ld / %.2ld \n", dividendo, divisor);
	result = dividendo / divisor;

	return &result;
}
