#include <rpc/rpc.h>        /* standard RPC include file */
#include "division.h"           /* this file is generated by rpcgen */



long* div_rpc_1(div_args divArgs)
{
    long result;    /* must be static */

    result = divArgs.dividendo / divArgs.divisor;
    return(&result);
}

