/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "division.h"

bool_t
xdr_div_args (XDR *xdrs, div_args *objp)
{
	register int32_t *buf;

	 if (!xdr_long (xdrs, &objp->dividendo))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->divisor))
		 return FALSE;
	return TRUE;
}
