/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "division.h"

long *
div_rpc_1_svc(div_args *argp, struct svc_req *rqstp)
{
	static long  result;

	/*
	 * insert server code here
	 */

	return &result;
}
